analyzers:
  sensors:
    type: GenericAnalyzer
    path: Sensors
    contains: [
      'hokuyo',
      'prosilica',
      'stereo',
      'forearm_camera',
      'imu' ]
  computers:
    type: GenericAnalyzer
    path: Computers
    contains: [
      'HD Temp',
      'CPU Usage',
      'CPU Temperature',
      'HD Usage',
      'NTP',
      'NFS']
  motors:
    type: GenericAnalyzer
    path: Motors
    startswith: [
      'EtherCAT Device']
    expected: [
      'EtherCAT Master',
      'EtherCAT Device (bl_caster_l_wheel_motor)',
      'EtherCAT Device (bl_caster_r_wheel_motor)',
      'EtherCAT Device (bl_caster_rotation_motor)',
      'EtherCAT Device (br_caster_l_wheel_motor)',
      'EtherCAT Device (br_caster_r_wheel_motor)',
      'EtherCAT Device (br_caster_rotation_motor)',
      'EtherCAT Device (fl_caster_l_wheel_motor)',
      'EtherCAT Device (fl_caster_r_wheel_motor)',
      'EtherCAT Device (fl_caster_rotation_motor)',
      'EtherCAT Device (fr_caster_l_wheel_motor)',
      'EtherCAT Device (fr_caster_r_wheel_motor)',
      'EtherCAT Device (fr_caster_rotation_motor)',
      'EtherCAT Device (head_pan_motor)',
      'EtherCAT Device (head_tilt_motor)',
      'EtherCAT Device (laser_tilt_mount_motor)',
      'EtherCAT Device (torso_lift_motor)',
      'EtherCAT Device (r_gripper_motor)',
      'EtherCAT Device (r_wrist_l_motor)',
      'EtherCAT Device (r_wrist_r_motor)',
      'EtherCAT Device (r_forearm_roll_motor)',
      'EtherCAT Device (r_elbow_flex_motor)',
      'EtherCAT Device (r_upper_arm_roll_motor)',
      'EtherCAT Device (r_shoulder_lift_motor)',
      'EtherCAT Device (r_shoulder_pan_motor)',
      'EtherCAT Device (l_gripper_motor)',
      'EtherCAT Device (l_wrist_l_motor)',
      'EtherCAT Device (l_wrist_r_motor)',
      'EtherCAT Device (l_forearm_roll_motor)',
      'EtherCAT Device (l_elbow_flex_motor)',
      'EtherCAT Device (l_upper_arm_roll_motor)',
      'EtherCAT Device (l_shoulder_lift_motor)',
      'EtherCAT Device (l_shoulder_pan_motor)']
  joints:
    type: GenericAnalyzer
    path: Joints
    startswith: [
      'Joint']
    expected: [
      'Joint (bl_caster_l_wheel_joint)',
      'Joint (bl_caster_r_wheel_joint)',
      'Joint (bl_caster_rotation_joint)',
      'Joint (br_caster_l_wheel_joint)',
      'Joint (br_caster_r_wheel_joint)',
      'Joint (br_caster_rotation_joint)',
      'Joint (fl_caster_l_wheel_joint)',
      'Joint (fl_caster_r_wheel_joint)',
      'Joint (fl_caster_rotation_joint)',
      'Joint (fr_caster_l_wheel_joint)',
      'Joint (fr_caster_r_wheel_joint)',
      'Joint (fr_caster_rotation_joint)',
      'Joint (head_pan_joint)',
      'Joint (head_tilt_joint)',
      'Joint (laser_tilt_mount_joint)',
      'Joint (torso_lift_joint)',
      'Joint (r_gripper_joint)',
      'Joint (r_wrist_flex_joint)',
      'Joint (r_wrist_roll_joint)',
      'Joint (r_forearm_roll_joint)',
      'Joint (r_elbow_flex_joint)',
      'Joint (r_upper_arm_roll_joint)',
      'Joint (r_shoulder_lift_joint)',
      'Joint (r_shoulder_pan_joint)',
      'Joint (l_gripper_joint)',
      'Joint (l_wrist_flex_joint)',
      'Joint (l_wrist_roll_joint)',
      'Joint (l_forearm_roll_joint)',
      'Joint (l_elbow_flex_joint)',
      'Joint (l_upper_arm_roll_joint)',
      'Joint (l_shoulder_lift_joint)',
      'Joint (l_shoulder_pan_joint)']
  power:
    type: GenericAnalyzer
    path: 'Power System'
    timeout: 10
    startswith: [
      'Power board',
      'IBPS',
      'Smart Battery']
    
