analyzers:
  sensors:
    type: GenericAnalyzer
    path: Sensors
    contains: [
      'hokuyo',
      'prosilica',
      'stereo',
      'forearm_camera',
      'imu' ]
  computers:
    type: GenericAnalyzer
    path: Computers
    contains: [
      'HD Temp',
      'CPU Usage',
      'CPU Temperature',
      'HD Usage',
      'NTP',
      'NFS']
  motors:
    type: GenericAnalyzer
    path: Motors
    startswith: [
      'EtherCAT Device']
    expected: [
      'EtherCAT Master',
      'EtherCAT Device (bl_caster_l_wheel_motor)',
      'EtherCAT Device (bl_caster_r_wheel_motor)',
      'EtherCAT Device (bl_caster_rotation_motor)',
      'EtherCAT Device (br_caster_l_wheel_motor)',
      'EtherCAT Device (br_caster_r_wheel_motor)',
      'EtherCAT Device (br_caster_rotation_motor)',
      'EtherCAT Device (fl_caster_l_wheel_motor)',
      'EtherCAT Device (fl_caster_r_wheel_motor)',
      'EtherCAT Device (fl_caster_rotation_motor)',
      'EtherCAT Device (fr_caster_l_wheel_motor)',
      'EtherCAT Device (fr_caster_r_wheel_motor)',
      'EtherCAT Device (fr_caster_rotation_motor)',
      'EtherCAT Device (head_pan_motor)',
      'EtherCAT Device (head_tilt_motor)',
      'EtherCAT Device (laser_tilt_mount_motor)',
      'EtherCAT Device (torso_lift_motor)']
  joints:
    type: GenericAnalyzer
    path: Joints
    startswith: [
      'Joint']
    expected: [
      'Joint (bl_caster_l_wheel_joint)',
      'Joint (bl_caster_r_wheel_joint)',
      'Joint (bl_caster_rotation_joint)',
      'Joint (br_caster_l_wheel_joint)',
      'Joint (br_caster_r_wheel_joint)',
      'Joint (br_caster_rotation_joint)',
      'Joint (fl_caster_l_wheel_joint)',
      'Joint (fl_caster_r_wheel_joint)',
      'Joint (fl_caster_rotation_joint)',
      'Joint (fr_caster_l_wheel_joint)',
      'Joint (fr_caster_r_wheel_joint)',
      'Joint (fr_caster_rotation_joint)',
      'Joint (head_pan_joint)',
      'Joint (head_tilt_joint)',
      'Joint (laser_tilt_mount_joint)',
      'Joint (torso_lift_joint)']
  power:
    type: GenericAnalyzer
    path: 'Power System'
    timeout: 10
    expected: [
      'Power board 1027',
      'IBPS 0',
      'IBPS 1',
      'IBPS 2',
      'IBPS 3',
      'Smart Battery 0.0',
      'Smart Battery 0.1',
      'Smart Battery 0.2',
      'Smart Battery 0.3',
      'Smart Battery 1.0',
      'Smart Battery 1.1',
      'Smart Battery 1.2',
      'Smart Battery 1.3',
      'Smart Battery 2.0',
      'Smart Battery 2.1',
      'Smart Battery 2.2',
      'Smart Battery 2.3',
      'Smart Battery 3.0',
      'Smart Battery 3.1',
      'Smart Battery 3.2',
      'Smart Battery 3.3']
    
